### PR TITLE
Count evolutions (does not account for second order evolutions yet)

### PR DESCRIPTION
**Pull request by kvanderkamp**
Players may use the number of possible evolutions to maximize XP gain from evolving Pokémon in combination with a Lucky Egg.

### CODE REVIEW

**Comment by cglatot** [comment]
A nice touch, but not fully thought-through from what I can see.

You only check if it can evolve - this means that your "countEvolutions" will be off because of the middle pokemon (E.G. Wartortle, etc). Since they share the same Candy as Squirtle, you will not be able to evolve both sets with the candies available, but the numbers _will_ be added to "countEvolutions. If I'm reading your code wrong, please let me know.

Also, I think rolling this functionality into the current "Count" menu will be better than having a separate menu item for it.

**Comment by kvanderkamp** [comment]
Thank you for reviewing.

Middle Pokemon are not counted, I've set their candies to 0 in "countEvolutions". This means they are never counted, even if there are enough candies left over after all of the first Pokemon have evolved. Will be looking into that

When i've fixed counting the middle Pokemon and merged this functionality into the "view counts" menu I'll make another pull request.

**Comment by kvanderkamp** [comment]
I see you added the evolve counts in already, nice.

**Comment by cglatot** [comment]
Ahhhh I see it now, you removed some of the try-catches to facilitate that.

If you fork my latest commit, that has your logic in it for counts, but _will_ count middle Pokemon.

The "total evolvable", I think, is more of a user expectation discussion rather than a technical one. I might add it as something like "Total evolutions of base pokemon" - in which case ignoring the second and third tier evolutions.

But I want to keep first and second tier "amounts to evolve" in the count view as I think it gives a good view in case you are looking to evolve certain pokemon (to get move sets, etc)

**Comment by cglatot** [comment]
Done. Shows total base evolutions available now :)

**Pull request closed without merging**
