### PR TITLE
Showing numbers of pokemon to transfer then evolve

### PR DESCRIPTION
**Pull request by BeardAnnihilator**
Calculate first the number of pokemon to transfer and then the updated number of pokemon to evolve.
Also the math is know taking consideration of the bonus candy after each evolution

### CODE REVIEW

**Comment by fprovostpoulin** [comment]
"Only for 12 candies pokemon" Would be a must in my opinion

**Comment by BeardAnnihilator** [comment]
Do you mean showing this column and updated number of evolution just for 12 candies Pokemons and not for the other ones ?

**Comment by fprovostpoulin** [comment]
Yes. The only pokemon you want to evolve in batch are pidgey, caterpie and weedles... which are the one providing easy exp

**Comment by BeardAnnihilator** [comment]
That's true, but having the information does not hurt right ?
While being more candy-expensive Rattata and Zubats are pretty common as well.

A screenshot of my zubats below, 
image

Note than technically there is enough candy just for 3 evolutions but by transferring and because of the evolution bonus candy, I can grind for a fourth evolution.

I could not transfer the Zubats and still be able to do 4 evolutions but I personally like to keep my pokemon count as low as possible.

So it tells how many I can transfer without loosing an opportunity of evolving.

**Comment by fprovostpoulin** [comment]
Same for me.

 For when is the batch evolution coming ?

_Félix Provost-Poulin_

Software Engeneer Bacc. and MBA Candidate
_Cellulaire : (514) 463-1978_

2016-08-09 22:19 GMT-04:00 Periphanos Alexandre notifications@github.com:

**Comment by BeardAnnihilator** [comment]
I realized the title of the pull-request was misleading, this code modification does not automatically transfer and evolve it just shows the optimum numbers for you to manually do it.

The actual batch evolution, hmmm, I am going to have a look !

**Comment by BeardAnnihilator** [comment]
To many changes - closing

**Pull request closed without merging**
